platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

target 'MemoryCity' do
  pod 'SDWebImage'
  pod 'YYModel'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'WCDB.objc'
  pod 'LookinServer', :configurations => ['Debug']
  target 'MemoryCityTests' do
    inherit! :search_paths
  end
  target 'MemoryCityUITests' do
    inherit! :search_paths
  end
end